/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author thiago.amanajas
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewApplication
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exportDataMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        customerMenu = new javax.swing.JMenu();
        searchCustomerMenuItem = new javax.swing.JMenuItem();
        addCustomerMenuItem = new javax.swing.JMenuItem();
        updateCustomerMenuItem = new javax.swing.JMenuItem();
        deleteCustomerMenuItem = new javax.swing.JMenuItem();
        rentalMenu = new javax.swing.JMenu();
        searchRentalMenuItem = new javax.swing.JMenuItem();
        updateRentalMenuItem = new javax.swing.JMenuItem();
        addRentalMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exportDataMenuItem.setMnemonic('a');
        exportDataMenuItem.setText("Export data ...");
        fileMenu.add(exportDataMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        customerMenu.setMnemonic('e');
        customerMenu.setText("Customer");

        searchCustomerMenuItem.setMnemonic('t');
        searchCustomerMenuItem.setText("Search");
        customerMenu.add(searchCustomerMenuItem);

        addCustomerMenuItem.setMnemonic('y');
        addCustomerMenuItem.setText("Add");
        customerMenu.add(addCustomerMenuItem);

        updateCustomerMenuItem.setMnemonic('p');
        updateCustomerMenuItem.setText("Update");
        customerMenu.add(updateCustomerMenuItem);

        deleteCustomerMenuItem.setMnemonic('d');
        deleteCustomerMenuItem.setText("Delete");
        customerMenu.add(deleteCustomerMenuItem);

        menuBar.add(customerMenu);

        rentalMenu.setMnemonic('h');
        rentalMenu.setText("Rental");

        searchRentalMenuItem.setMnemonic('c');
        searchRentalMenuItem.setText("Search");
        rentalMenu.add(searchRentalMenuItem);

        updateRentalMenuItem.setMnemonic('a');
        updateRentalMenuItem.setText("Update");
        rentalMenu.add(updateRentalMenuItem);

        addRentalMenuItem.setText("Add");
        rentalMenu.add(addRentalMenuItem);

        menuBar.add(rentalMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCustomerMenuItem;
    private javax.swing.JMenuItem addRentalMenuItem;
    private javax.swing.JMenu customerMenu;
    private javax.swing.JMenuItem deleteCustomerMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exportDataMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu rentalMenu;
    private javax.swing.JMenuItem searchCustomerMenuItem;
    private javax.swing.JMenuItem searchRentalMenuItem;
    private javax.swing.JMenuItem updateCustomerMenuItem;
    private javax.swing.JMenuItem updateRentalMenuItem;
    // End of variables declaration//GEN-END:variables

}
