/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controllers.RentController;
import controllers.WindowController;
import entities.Category;
import entities.IEntity;
import entities.Rental;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;

/**
 *
 * @author thiago.amanajas
 */
public class RentalForm extends Window {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3266934888347739601L;
	/**
	 * 
	 */
	public static final String NAME = "rentalForm";
    private final RentController rentController;
    private Rental rental;
    /**
     * Creates new form RentalForm
     */
    public RentalForm() {
        super(NAME);
        initComponents();
        this.rental = null;
        this.rentController = new RentController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        cancelButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		formWindowClosed(null);
        	}
        });
        saveButton = new javax.swing.JButton();
        saveButton.addActionListener(new ActionListener() {
        	@Override
        	public void actionPerformed(ActionEvent e) {
        		String title = titleField.getText();
				Category category = rentController.getCategory((String) categoryCombo.getSelectedItem());
				boolean operation;
				if (rental == null) {
					operation = rentController.addRent(title, category);
				} else {
					operation = rentController.updateRent(rental, title, category);
				}
				if (!operation) {
					JOptionPane.showMessageDialog(RentalForm.this,
				            "It was not possible to save the rental.",
				            "warning",
				            JOptionPane.ERROR_MESSAGE);
				} else {
					JOptionPane.showMessageDialog(RentalForm.this,
				            "The rental was saved.",
				            "info",
				            JOptionPane.PLAIN_MESSAGE);
					formWindowClosed(null);
				}
        	}
        });

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Customer form");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setResizable(false);

        categoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membershipTypeComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Category");

        jLabel2.setText("Title");

        cancelButton.setText("Cancel");

        saveButton.setText("Save");
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(titleField, GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
        								.addComponent(jLabel2))
        							.addGap(0, 53, Short.MAX_VALUE))
        						.addComponent(jLabel1))
        					.addContainerGap())
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(categoryCombo, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addGap(59))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(cancelButton)
        					.addPreferredGap(ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
        					.addComponent(saveButton)
        					.addContainerGap())))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(39)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(titleField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(categoryCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(cancelButton)
        				.addComponent(saveButton))
        			.addGap(81))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.rental = null;
        WindowController.getInstance().showMainWindow();
    }//GEN-LAST:event_formWindowClosed
    
    private void membershipTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membershipTypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_membershipTypeComboActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JTextField titleField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clear() {
        this.titleField.setText("");
        refreshCombo();
        this.categoryCombo.setSelectedIndex(0);
    }
    
    public void openRental(Rental rental) {
        this.rental = rental;
        this.titleField.setText(rental.getTitle());
        refreshCombo(rental.getCategory());
    }

    @Override
    public Window copy() {
        return new RentalForm();
    }

    private void refreshCombo() {
    	ComboModel model = new ComboModel();
    	List<IEntity> list = List.copyOf(this.rentController.getCategories());
        model.setOptionList(list);
        this.categoryCombo.setModel(model);
    }

    private void refreshCombo(IEntity category) {
        refreshCombo();
        this.categoryCombo.setSelectedItem(category);
    }

}
