/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controllers.WindowController;
import db.Database;
import entities.Rental;
import entities.User;
import gui.components.AutoComplete;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.KeyStroke;

/**
 *
 * @author thiago.amanajas
 */
public class RentStatusForm extends Window {
    
    public static final String NAME = "rentStatus";
    private List<User> users;
    private List<Rental> rentals;
    
    /**
     * Creates new form RentStatusForm
     */
    public RentStatusForm() {
        super(NAME);
        initComponents();
        updateFields();
    }
    
    private void updateFields() {
        try {
            this.users = Database.getInstance().getUser().getAll();
            this.rentals = Database.getInstance().getRental().getAll();
            List<String> autoCompleteUserIDs = new ArrayList<>();
            List<String> autoCompleteUsers = new ArrayList<>();
            List<String> autoCompleteRentals = new ArrayList<>();
            for (int i = 0; i < users.size(); i++) {
                autoCompleteUserIDs.add(String.valueOf(users.get(i).getId()));
                autoCompleteUsers.add(users.get(i).getName());
            }
            for (int i = 0; i < rentals.size(); i++) {
                autoCompleteRentals.add(rentals.get(i).getTitle());
            }
            this.customerIDField.setFocusTraversalKeysEnabled(false);
            this.customerNameField.setFocusTraversalKeysEnabled(false);
            this.rentalTitleSearchField.setFocusTraversalKeysEnabled(false);
            AutoComplete autoCompleteId = new AutoComplete(this.customerIDField, autoCompleteUserIDs);
            AutoComplete autoCompleteName = new AutoComplete(this.customerNameField, autoCompleteUsers);
            AutoComplete autoCompleteTitle = new AutoComplete(this.rentalTitleSearchField, autoCompleteRentals);
            this.customerIDField.getDocument().addDocumentListener(autoCompleteId);
            this.customerNameField.getDocument().addDocumentListener(autoCompleteName);
            this.rentalTitleSearchField.getDocument().addDocumentListener(autoCompleteTitle);
            
            this.customerIDField.getInputMap().put(KeyStroke.getKeyStroke("TAB"), AutoComplete.COMMIT_ACTION);
            this.customerIDField.getActionMap().put(AutoComplete.COMMIT_ACTION, autoCompleteId.new CommitAction());
        } catch (SQLException ex) {
            Logger.getLogger(RentStatusForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customerIDField = new javax.swing.JTextField();
        rentalTitleSearchField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        updateStatusButton = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rent status");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        customerNameField.setToolTipText("Type the name of the customer");

        jLabel1.setText("Customer name:");

        jLabel2.setText("Customer ID:");

        customerIDField.setToolTipText("Type the ID of the customer");

        rentalTitleSearchField.setToolTipText("Type the rental title");

        jLabel3.setText("Rental title:");

        saveButton.setText("Save");

        updateStatusButton.setText("Active");

        jLabel4.setText("Rent status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(updateStatusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rentalTitleSearchField)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 43, Short.MAX_VALUE))
                            .addComponent(customerIDField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentalTitleSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(updateStatusButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        WindowController.getInstance().showMainWindow();
    }//GEN-LAST:event_formWindowClosed


    @Override
    public Window copy() {
        return new RentStatusForm();
    }

    @Override
    public void clear() {
        // TODO: Clear all fields
    }

    public void setSelectedRentStatus(User user, Rental rental) {
        this.customerIDField.setText(String.valueOf(user.getId()));
        this.customerNameField.setText(String.valueOf(user.getName()));
        this.rentalTitleSearchField.setText(rental.getTitle());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customerIDField;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField rentalTitleSearchField;
    private javax.swing.JButton saveButton;
    private javax.swing.JToggleButton updateStatusButton;
    // End of variables declaration//GEN-END:variables

}
